inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: "2.5"

Metrics/ParameterLists:
  Max: 8
Naming/FileName:
  Exclude:
    - lib/sidekiq-datadog.rb
RSpec/MultipleMemoizedHelpers:
  Enabled: false
