require: rubocop-performance
inherit_from:
  - https://gitlab.com/bsm/misc/raw/master/rubocop/default.yml
AllCops:
  TargetRubyVersion: "2.3"
Naming/FileName:
  Exclude:
    - "lib/sidekiq-datadog.rb"
    - "sidekiq-datadog.gemspec"
