name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.5", "2.6", "2.7", "3.0"]
        gemfile: [ Gemfile, Gemfile_dogstats_v4 ]
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake
